package com.english.easyenglish.pojo;

import java.io.Serializable;

/**
 * 分类表
 * @TableName category
 */
public class Category implements Serializable {
    /**
     * id
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    private Long categoryid;

    /**
     * 名称
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    private String name;

    /**
     * 排序
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    private static final long serialVersionUID = 1L;

    /**
     * id
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    public Long getCategoryid() {
        return categoryid;
    }

    /**
     * id
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    public void setCategoryid(Long categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * 名称
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    public String getName() {
        return name;
    }

    /**
     * 名称
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 排序
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * 排序
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Category other = (Category) that;
        return (this.getCategoryid() == null ? other.getCategoryid() == null : this.getCategoryid().equals(other.getCategoryid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getOrder() == null ? other.getOrder() == null : this.getOrder().equals(other.getOrder()));
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCategoryid() == null) ? 0 : getCategoryid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getOrder() == null) ? 0 : getOrder().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:03
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", categoryid=").append(categoryid);
        sb.append(", name=").append(name);
        sb.append(", order=").append(order);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}