package com.english.easyenglish.pojo;

import java.io.Serializable;

/**
 * 收藏表
 * @TableName collect
 */
public class Collect implements Serializable {
    /**
     * 收藏表主键
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    private Long collectid;

    /**
     * 单词本外键
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    private Long wordidfk;

    /**
     * 用户外键
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collect
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    private static final long serialVersionUID = 1L;

    /**
     * 收藏表主键
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    public Long getCollectid() {
        return collectid;
    }

    /**
     * 收藏表主键
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    public void setCollectid(Long collectid) {
        this.collectid = collectid;
    }

    /**
     * 单词本外键
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    public Long getWordidfk() {
        return wordidfk;
    }

    /**
     * 单词本外键
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    public void setWordidfk(Long wordidfk) {
        this.wordidfk = wordidfk;
    }

    /**
     * 用户外键
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * 用户外键
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Collect other = (Collect) that;
        return (this.getCollectid() == null ? other.getCollectid() == null : this.getCollectid().equals(other.getCollectid()))
            && (this.getWordidfk() == null ? other.getWordidfk() == null : this.getWordidfk().equals(other.getWordidfk()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()));
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCollectid() == null) ? 0 : getCollectid().hashCode());
        result = prime * result + ((getWordidfk() == null) ? 0 : getWordidfk().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:12
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", collectid=").append(collectid);
        sb.append(", wordidfk=").append(wordidfk);
        sb.append(", userid=").append(userid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}