package com.english.easyenglish.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * 错题表
 * @TableName errors
 */
public class Errors implements Serializable {
    /**
     * 错题表id
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    private Long errorsid;

    /**
     * 单词表id
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    private Long wordId;

    /**
     * 创建时间
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    private Date createtime;

    /**
     * 创建用户
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table errors
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    private static final long serialVersionUID = 1L;

    /**
     * 错题表id
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    public Long getErrorsid() {
        return errorsid;
    }

    /**
     * 错题表id
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    public void setErrorsid(Long errorsid) {
        this.errorsid = errorsid;
    }

    /**
     * 单词表id
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    public Long getWordId() {
        return wordId;
    }

    /**
     * 单词表id
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    public void setWordId(Long wordId) {
        this.wordId = wordId;
    }

    /**
     * 创建时间
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * 创建时间
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * 创建用户
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * 创建用户
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Errors other = (Errors) that;
        return (this.getErrorsid() == null ? other.getErrorsid() == null : this.getErrorsid().equals(other.getErrorsid()))
            && (this.getWordId() == null ? other.getWordId() == null : this.getWordId().equals(other.getWordId()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getCreateuser() == null ? other.getCreateuser() == null : this.getCreateuser().equals(other.getCreateuser()));
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getErrorsid() == null) ? 0 : getErrorsid().hashCode());
        result = prime * result + ((getWordId() == null) ? 0 : getWordId().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getCreateuser() == null) ? 0 : getCreateuser().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:21
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", errorsid=").append(errorsid);
        sb.append(", wordId=").append(wordId);
        sb.append(", createtime=").append(createtime);
        sb.append(", createuser=").append(createuser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}