package com.english.easyenglish.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * 试卷主表
 * @TableName examination
 */
public class Examination implements Serializable {
    /**
     * 试卷id
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    private Long examinationid;

    /**
     * 试卷名称
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    private String name;

    /**
     * 得分
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    private Integer score;

    /**
     * 卷面总分
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    private Integer totalpoints;

    /**
     * 试卷主表创建时间
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    private Date createdate;

    /**
     * 试卷创建人
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table examination
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    private static final long serialVersionUID = 1L;

    /**
     * 试卷id
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    public Long getExaminationid() {
        return examinationid;
    }

    /**
     * 试卷id
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    public void setExaminationid(Long examinationid) {
        this.examinationid = examinationid;
    }

    /**
     * 试卷名称
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    public String getName() {
        return name;
    }

    /**
     * 试卷名称
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 得分
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    public Integer getScore() {
        return score;
    }

    /**
     * 得分
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * 卷面总分
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    public Integer getTotalpoints() {
        return totalpoints;
    }

    /**
     * 卷面总分
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    public void setTotalpoints(Integer totalpoints) {
        this.totalpoints = totalpoints;
    }

    /**
     * 试卷主表创建时间
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * 试卷主表创建时间
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * 试卷创建人
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * 试卷创建人
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Examination other = (Examination) that;
        return (this.getExaminationid() == null ? other.getExaminationid() == null : this.getExaminationid().equals(other.getExaminationid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
            && (this.getTotalpoints() == null ? other.getTotalpoints() == null : this.getTotalpoints().equals(other.getTotalpoints()))
            && (this.getCreatedate() == null ? other.getCreatedate() == null : this.getCreatedate().equals(other.getCreatedate()))
            && (this.getCreateuser() == null ? other.getCreateuser() == null : this.getCreateuser().equals(other.getCreateuser()));
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getExaminationid() == null) ? 0 : getExaminationid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        result = prime * result + ((getTotalpoints() == null) ? 0 : getTotalpoints().hashCode());
        result = prime * result + ((getCreatedate() == null) ? 0 : getCreatedate().hashCode());
        result = prime * result + ((getCreateuser() == null) ? 0 : getCreateuser().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:32
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", examinationid=").append(examinationid);
        sb.append(", name=").append(name);
        sb.append(", score=").append(score);
        sb.append(", totalpoints=").append(totalpoints);
        sb.append(", createdate=").append(createdate);
        sb.append(", createuser=").append(createuser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}