package com.english.easyenglish.pojo;

import java.io.Serializable;

/**
 * 试卷题目表(单词和试卷中间表)
 * @TableName examinationitem
 */
public class Examinationitem implements Serializable {
    /**
     * id
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    private Long examinationitemid;

    /**
     * 单词id外键
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    private Long wordidfk;

    /**
     * 试卷id外键
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    private Long examinationidfk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table examinationitem
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    private static final long serialVersionUID = 1L;

    /**
     * id
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    public Long getExaminationitemid() {
        return examinationitemid;
    }

    /**
     * id
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    public void setExaminationitemid(Long examinationitemid) {
        this.examinationitemid = examinationitemid;
    }

    /**
     * 单词id外键
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    public Long getWordidfk() {
        return wordidfk;
    }

    /**
     * 单词id外键
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    public void setWordidfk(Long wordidfk) {
        this.wordidfk = wordidfk;
    }

    /**
     * 试卷id外键
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    public Long getExaminationidfk() {
        return examinationidfk;
    }

    /**
     * 试卷id外键
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    public void setExaminationidfk(Long examinationidfk) {
        this.examinationidfk = examinationidfk;
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Examinationitem other = (Examinationitem) that;
        return (this.getExaminationitemid() == null ? other.getExaminationitemid() == null : this.getExaminationitemid().equals(other.getExaminationitemid()))
            && (this.getWordidfk() == null ? other.getWordidfk() == null : this.getWordidfk().equals(other.getWordidfk()))
            && (this.getExaminationidfk() == null ? other.getExaminationidfk() == null : this.getExaminationidfk().equals(other.getExaminationidfk()));
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getExaminationitemid() == null) ? 0 : getExaminationitemid().hashCode());
        result = prime * result + ((getWordidfk() == null) ? 0 : getWordidfk().hashCode());
        result = prime * result + ((getExaminationidfk() == null) ? 0 : getExaminationidfk().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:43
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", examinationitemid=").append(examinationitemid);
        sb.append(", wordidfk=").append(wordidfk);
        sb.append(", examinationidfk=").append(examinationidfk);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}