package com.english.easyenglish.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * 单词本
 * @TableName word
 */
public class Word implements Serializable {
    /**
     * 单词本主键
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    private Long wordid;

    /**
     * 英文
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    private String us;

    /**
     * 中文
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    private String cn;

    /**
     * 类别外键
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    private Long categoryidfk;

    /**
     * 父id
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    private Long pid;

    /**
     * 音标
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    private String phonetic;

    /**
     * 创建时间
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    private Date createtime;

    /**
     * 创建人
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    private static final long serialVersionUID = 1L;

    /**
     * 单词本主键
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public Long getWordid() {
        return wordid;
    }

    /**
     * 单词本主键
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public void setWordid(Long wordid) {
        this.wordid = wordid;
    }

    /**
     * 英文
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public String getUs() {
        return us;
    }

    /**
     * 英文
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public void setUs(String us) {
        this.us = us;
    }

    /**
     * 中文
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public String getCn() {
        return cn;
    }

    /**
     * 中文
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public void setCn(String cn) {
        this.cn = cn;
    }

    /**
     * 类别外键
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public Long getCategoryidfk() {
        return categoryidfk;
    }

    /**
     * 类别外键
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public void setCategoryidfk(Long categoryidfk) {
        this.categoryidfk = categoryidfk;
    }

    /**
     * 父id
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public Long getPid() {
        return pid;
    }

    /**
     * 父id
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * 音标
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public String getPhonetic() {
        return phonetic;
    }

    /**
     * 音标
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public void setPhonetic(String phonetic) {
        this.phonetic = phonetic;
    }

    /**
     * 创建时间
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * 创建时间
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * 创建人
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * 创建人
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Word other = (Word) that;
        return (this.getWordid() == null ? other.getWordid() == null : this.getWordid().equals(other.getWordid()))
            && (this.getUs() == null ? other.getUs() == null : this.getUs().equals(other.getUs()))
            && (this.getCn() == null ? other.getCn() == null : this.getCn().equals(other.getCn()))
            && (this.getCategoryidfk() == null ? other.getCategoryidfk() == null : this.getCategoryidfk().equals(other.getCategoryidfk()))
            && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getPhonetic() == null ? other.getPhonetic() == null : this.getPhonetic().equals(other.getPhonetic()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getCreateuser() == null ? other.getCreateuser() == null : this.getCreateuser().equals(other.getCreateuser()));
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getWordid() == null) ? 0 : getWordid().hashCode());
        result = prime * result + ((getUs() == null) ? 0 : getUs().hashCode());
        result = prime * result + ((getCn() == null) ? 0 : getCn().hashCode());
        result = prime * result + ((getCategoryidfk() == null) ? 0 : getCategoryidfk().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getPhonetic() == null) ? 0 : getPhonetic().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getCreateuser() == null) ? 0 : getCreateuser().hashCode());
        return result;
    }

    /**
     *
     * @mbg.generated 2021-08-18 13:56:59
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", wordid=").append(wordid);
        sb.append(", us=").append(us);
        sb.append(", cn=").append(cn);
        sb.append(", categoryidfk=").append(categoryidfk);
        sb.append(", pid=").append(pid);
        sb.append(", phonetic=").append(phonetic);
        sb.append(", createtime=").append(createtime);
        sb.append(", createuser=").append(createuser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}